services:
  - type: worker
    name: telegram-anon-bot
    env: python
    runtime: python
    pythonVersion: "3.11.0"
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: anonymous-bot-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.0"
